from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import VendorPerformance

router = DefaultRouter()

# Registering the VendorPerformanceViewSet with the router
router.register('performance', VendorPerformance, basename='vendor_performance')

# Defining URL patterns
urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
]
